#!/usr/bin/env python3
"""Storage-profile helpers for the PM9A3/SimpleSSD + Resa pipeline scripts.

The current paper-number path is generated by run_csd_integrated.py and
run_csd_scaling.py. This module keeps the shared parsing and storage-stream
helpers used by those scripts.

The storage producer is described by explicit SimpleSSD-like fields. Physical
PM9A3 fio rows are validation anchors for the selected parameter vector.
"""

from __future__ import annotations

import csv
import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

from resa_datapath import DataLayout, DatapathConfig, compute_group_timing, writeback_timing


SCRIPT_DIR = Path(__file__).resolve().parent
ARTIFACT_DIR = SCRIPT_DIR.parent
DEFAULT_SIMPLESSD_SUMMARY = (
    SCRIPT_DIR / "results" / "pm9a3-simplessd-official-seq-selected-260530" / "sim_summary.csv"
)
DEFAULT_SIMPLESSD_CONFIG_DIR = (
    SCRIPT_DIR / "results" / "pm9a3-simplessd-official-seq-selected-260530" / "configs"
)
DEFAULT_MEASURED_CSV = (
    SCRIPT_DIR / "results" / "pm9a3-allocated-file-read-260530" / "summary_for_simplessd.csv"
)
DEFAULT_DATAPATH_PROFILE = SCRIPT_DIR / "profiles" / "resa-datapath-selected.json"
DEFAULT_CANDIDATE = "officialseq_pg8_tr5_8_12_stack42_dma3000m_sram425_2cy"
DEFAULT_WORKLOAD = "hold_seqread_1m_qd8"
MB = 1_000_000.0


def artifact_path(path: str | Path) -> str:
    p = Path(path)
    try:
        return str(p.relative_to(ARTIFACT_DIR))
    except ValueError:
        return str(p)


def parse_size_bytes(value: str) -> int:
    m = re.fullmatch(r"(\d+)([KMGTPkmgtp]?)", str(value))
    if not m:
        raise ValueError(f"unsupported size: {value}")
    n = int(m.group(1))
    suffix = m.group(2)
    if not suffix:
        return n
    if suffix in "kmgtp":
        return n * (1000 ** ("kmgtp".index(suffix) + 1))
    return n * (1024 ** ("KMGTP".index(suffix) + 1))


def parse_rate_bytes_s(value: str) -> float:
    m = re.fullmatch(r"([0-9.]+)([kKmMgGtT]?)", str(value))
    if not m:
        raise ValueError(f"unsupported rate: {value}")
    n = float(m.group(1))
    suffix = m.group(2).lower()
    scale = {"": 1.0, "k": 1e3, "m": 1e6, "g": 1e9, "t": 1e12}[suffix]
    return n * scale


def parse_latency_s(value: str) -> float:
    m = re.fullmatch(r"([0-9.]+)(ps|ns|us|ms|s)", str(value))
    if not m:
        if str(value) == "0":
            return 0.0
        raise ValueError(f"unsupported latency: {value}")
    n = float(m.group(1))
    scale = {"ps": 1e-12, "ns": 1e-9, "us": 1e-6, "ms": 1e-3, "s": 1.0}[m.group(2)]
    return n * scale


def load_tree(path: Path) -> ET.ElementTree:
    text = path.read_text()
    text = re.sub(r"<\?xml[^>]*\?>", "", text, count=1)
    return ET.ElementTree(ET.fromstring(text))


def section(root: ET.Element, names: list[str]) -> ET.Element:
    node = root
    for name in names:
        found = None
        for child in node:
            if child.tag == "section" and child.attrib.get("name") == name:
                found = child
                break
        if found is None:
            raise KeyError("missing section " + "/".join(names))
        node = found
    return node


def config_text(root: ET.Element, section_path: list[str], name: str, attrib: dict[str, str] | None = None) -> str:
    sec = section(root, section_path)
    for child in sec:
        if child.tag != "config" or child.attrib.get("name") != name:
            continue
        if attrib and any(child.attrib.get(k) != str(v) for k, v in attrib.items()):
            continue
        return (child.text or "").strip()
    raise KeyError("missing config " + "/".join(section_path + [name]))


def parse_simplessd_row(path: Path, candidate: str, workload: str) -> dict[str, str] | None:
    if not path.exists():
        return None
    with path.open(newline="") as f:
        rows = [
            row for row in csv.DictReader(f)
            if row["candidate"] == candidate
            and row["workload"] == workload
            and row["status"] == "ok"
        ]
    if not rows:
        return None
    if len(rows) > 1:
        raise SystemExit(
            f"multiple rows matched candidate={candidate!r}, workload={workload!r} in {path}"
        )
    return rows[0]


def parse_measured_row(path: Path, workload: str) -> dict[str, str] | None:
    if not path.exists():
        return None
    names = [workload]
    if workload.startswith("hold_"):
        names.append("alloc_" + workload[len("hold_"):])
    elif workload.startswith("cal_"):
        names.append("alloc_" + workload[len("cal_"):])
    wanted = set(names)
    with path.open(newline="") as f:
        for row in csv.DictReader(f):
            if row["name"] in wanted:
                return row
    return None


def parse_candidate_config(path: Path) -> dict[str, Any]:
    tree = load_tree(path)
    root = tree.getroot()

    tr_values: dict[str, str] = {}
    timing = section(root, ["fil", "nand", "timing"])
    for child in timing:
        if child.tag == "config" and child.attrib.get("name") == "tR":
            level = child.attrib.get("level", "all")
            tr_values[level] = (child.text or "").strip()

    page_size = config_text(root, ["fil", "nand"], "PageSize")
    dma_speed = config_text(root, ["fil", "nand"], "DMASpeed")
    data_width = config_text(root, ["fil", "nand"], "DataWidth")

    return {
        "pcie_generation": int(config_text(root, ["hil", "interface", "pcie"], "Generation")),
        "pcie_lanes": int(config_text(root, ["hil", "interface", "pcie"], "Lane")),
        "channel": int(config_text(root, ["fil"], "Channel")),
        "way": int(config_text(root, ["fil"], "Way")),
        "die": int(config_text(root, ["fil", "nand"], "Die")),
        "plane": int(config_text(root, ["fil", "nand"], "Plane")),
        "page_size": page_size,
        "page_size_bytes": parse_size_bytes(page_size),
        "page_per_block": int(config_text(root, ["fil", "nand"], "Page")),
        "nop": int(config_text(root, ["fil", "nand"], "NOP")),
        "superpage_allocation": config_text(root, ["ftl", "common"], "SuperpageAllocation"),
        "page_allocation": config_text(root, ["fil", "nand"], "PageAllocation"),
        "nand_type": int(config_text(root, ["fil", "nand"], "NANDType")),
        "dma_speed": dma_speed,
        "dma_speed_bytes_s": parse_rate_bytes_s(dma_speed),
        "data_width_bytes": int(data_width),
        "tr": tr_values,
        "tr_s": {level: parse_latency_s(value) for level, value in tr_values.items()},
        "tprog": {
            "0": config_text(root, ["fil", "nand", "timing"], "tPROG", {"level": "0"}),
            "1": config_text(root, ["fil", "nand", "timing"], "tPROG", {"level": "1"}),
            "2": config_text(root, ["fil", "nand", "timing"], "tPROG", {"level": "2"}),
        },
        "cache_mode": config_text(root, ["icl"], "CacheMode"),
        "read_prefetch": config_text(root, ["icl", "prefetch"], "EnableReadPrefetch"),
        "hil_work_interval": config_text(root, ["hil"], "WorkInterval"),
        "hil_request_queue_size": int(config_text(root, ["hil"], "RequestQueueSize")),
    }


def avg_tr_s(params: dict[str, Any]) -> float:
    values = params["tr_s"]
    if "all" in values:
        return values["all"]
    return sum(values[k] for k in sorted(values)) / len(values)


def internal_storage_stream(
    *,
    params: dict[str, Any],
    row: dict[str, str] | None,
    measured: dict[str, str] | None,
    read_granularity: str,
    efficiency: float | None,
) -> dict[str, Any]:
    page_bytes = params["page_size_bytes"]
    channel = params["channel"]

    # SimpleSSD's NAND DMA timing is one transfer per DataWidth at DMASpeed.
    # Keep this as an explicit per-page transfer component in the profile.
    dma1_s = page_bytes / params["data_width_bytes"] / params["dma_speed_bytes_s"]
    tr_s = avg_tr_s(params)
    page_service_s = tr_s + dma1_s
    raw_page_bw = channel * page_bytes / page_service_s

    if read_granularity == "measured_seq":
        if measured is None:
            raise SystemExit("--read-granularity measured_seq requires --measured-csv row")
        anchor_bw = float(measured["bw_mb_s"]) * MB
        source = "physical_pm9a3_seq_anchor"
        eff = anchor_bw / raw_page_bw
        bw = anchor_bw
    elif read_granularity == "simplessd_seq":
        if row is None:
            raise SystemExit("--read-granularity simplessd_seq requires --summary-csv row")
        anchor_bw = float(row["sim_bw_mb_s"]) * MB
        source = "simplessd_host_read_validation"
        eff = anchor_bw / raw_page_bw
        bw = anchor_bw
    elif read_granularity == "parameter_raw":
        eff = 1.0 if efficiency is None else efficiency
        source = "parameter_raw"
        bw = raw_page_bw * eff
    else:
        raise SystemExit(f"unsupported read granularity: {read_granularity}")

    return {
        "source": source,
        "bw_bytes_s": bw,
        "bw_mb_s": bw / MB,
        "raw_page_bw_mb_s": raw_page_bw / MB,
        "efficiency_vs_raw": eff,
        "page_service_us": page_service_s * 1_000_000.0,
        "avg_tr_us": tr_s * 1_000_000.0,
        "dma1_us": dma1_s * 1_000_000.0,
        "read_parallel_units": channel,
    }
